export const CATALOG_STORAGE_KEY = "kushi-agro-catalog";

export const defaultCatalog = [
  {
    id: "01",
    name: "Zanda Executive Range",
    tagline: "Premium quality rice",
    pack: "25 KG",
    views: 3,
    accent: "from-[#18432A] to-[#6B8D58]",
  },
  {
    id: "02",
    name: "Zanda Blue Pack",
    tagline: "Premium quality rice",
    pack: "25 KG",
    views: 2,
    accent: "from-[#2848A1] to-[#7A89E8]",
  },
  {
    id: "03",
    name: "Zanda Exclusive Range",
    tagline: "Premium quality rice",
    pack: "25 KG",
    views: 3,
    accent: "from-[#A93D2D] to-[#E58B6E]",
  },
  {
    id: "04",
    name: "Small Boss Platinum Range",
    tagline: "Happy Special Blue Lam steam rice",
    pack: "25 KG",
    views: 3,
    accent: "from-[#6B124E] to-[#F08BBF]",
  },
  {
    id: "05",
    name: "Golden Chill Exclusive Range",
    tagline: "Monsoon Sona Masuri raw rice",
    pack: "25 KG",
    views: 2,
    accent: "from-[#9A2915] to-[#F0B23B]",
  },
  {
    id: "06",
    name: "Golden Chill Economical Range",
    tagline: "New Sona Masuri raw rice",
    pack: "25 KG",
    views: 2,
    accent: "from-[#171717] to-[#828282]",
  },
  {
    id: "07",
    name: "Royal Bullet Rice",
    tagline: "Jeera rice biryani special",
    pack: "10 KG",
    views: 2,
    accent: "from-[#2391D8] to-[#A1D9FF]",
  },
  {
    id: "08",
    name: "Happy Special Premium Sortex",
    tagline: "Premium sortex quality rice",
    pack: "KG pack available",
    views: 3,
    accent: "from-[#3A287C] to-[#BFA2FF]",
  },
  {
    id: "09",
    name: "Happy Special Jeera Rice",
    tagline: "Marriage special biryani colom rice",
    pack: "26 KG",
    views: 1,
    accent: "from-[#171717] to-[#796D5E]",
  },
  {
    id: "10",
    name: "Happy Special Premium Sorted",
    tagline: "Premium sorted quality rice",
    pack: "25 KG",
    views: 2,
    accent: "from-[#22358C] to-[#7AA7FF]",
  },
  {
    id: "11",
    name: "M Platinum Range",
    tagline: "Happy Special Blue Lam steam rice",
    pack: "KG pack available",
    views: 2,
    accent: "from-[#B11F21] to-[#FF8A8D]",
  },
  {
    id: "12",
    name: "M Jeera Rice Black Pack",
    tagline: "Lachkari Wada Kolam biryani special",
    pack: "25 KG",
    views: 2,
    accent: "from-[#111111] to-[#696969]",
  },
  {
    id: "13",
    name: "M Jeera Rice Red Pack",
    tagline: "Lachkari Wada Kolam biryani special",
    pack: "25 KG",
    views: 2,
    accent: "from-[#A51217] to-[#E87073]",
  },
  {
    id: "14",
    name: "Royal Bullet Rice Pink Pack",
    tagline: "Jeera rice marriage special biryani colom rice",
    pack: "25 KG",
    views: 3,
    accent: "from-[#B2109C] to-[#FF88E4]",
  },
  {
    id: "15",
    name: "Royal Bullet Rice Green Pack",
    tagline: "Jeera rice marriage special biryani colom rice",
    pack: "25 KG",
    views: 2,
    accent: "from-[#136838] to-[#7FCC95]",
  },
  {
    id: "16",
    name: "Royal Bullet Rice Red Pack",
    tagline: "Jeera rice marriage special biryani colom rice",
    pack: "25 KG",
    views: 3,
    accent: "from-[#941312] to-[#E66B67]",
  },
  {
    id: "17",
    name: "Royal Bullet Rice Orange Pack",
    tagline: "Jeera rice marriage special biryani colom rice",
    pack: "25 KG",
    views: 3,
    accent: "from-[#B96512] to-[#FFBB58]",
  },
  {
    id: "18",
    name: "Royal Bullet Rice Blue Pack",
    tagline: "Jeera rice marriage special biryani colom rice",
    pack: "25 KG",
    views: 3,
    accent: "from-[#1978BF] to-[#83CCFF]",
  },
  {
    id: "RS",
    name: "Royal Special Rice",
    tagline: "Premium quality aged rice",
    pack: "25 KG",
    views: 3,
    accent: "from-[#8B6D10] to-[#D8C15A]",
    coverImage: "/images/royal_special_1.jpeg",
    images: ["/images/royal_special_1.jpeg", "/images/royal_special_2.jpeg", "/images/royal_special_3.jpeg"],
  },
  {
    id: "21",
    name: "Vandematharam Special Range",
    tagline: "Premium bullet rice old HMT",
    pack: "25 KG",
    views: 2,
    accent: "from-[#A48B14] to-[#F1D45B]",
  },

  {
    id: "22",
    name: "Vande Mataram Premium Sorted",
    tagline: "Raichur Sona Masuri rice",
    pack: "10 KG",
    views: 2,
    accent: "from-[#D65C12] to-[#F0C853]",
  },
  {
    id: "23",
    name: "Vande Mataram Premium Sorted",
    tagline: "Premium sorted rice",
    pack: "25 KG",
    views: 3,
    accent: "from-[#D96A1F] to-[#F4D17F]",
  },
  {
    id: "24",
    name: "Vandematharam Gold Range",
    tagline: "One year old raw rice",
    pack: "25 KG",
    views: 3,
    accent: "from-[#394C9E] to-[#93A4F2]",
  },
  {
    id: "25",
    name: "Vandematharam Gold Range",
    tagline: "Grand old raw rice",
    pack: "25 KG",
    views: 3,
    accent: "from-[#8B6D10] to-[#D8C15A]",
  },
  {
    id: "26",
    name: "M Platinum Range Fine Bullet Rice",
    tagline: "Ultra quality fine bullet rice",
    pack: "KG pack available",
    views: 1,
    accent: "from-[#9E178A] to-[#F36DDA]",
  },
];

export function buildCatalogProducts(catalog) {
  return catalog.map((product) => ({
    ...product,
    coverImage: product.coverImage || `/images/catalog/product-${product.id}/view-01.jpeg`,
    images:
      product.images ||
      Array.from(
        { length: product.views },
        (_, index) =>
          `/images/catalog/product-${product.id}/view-${String(index + 1).padStart(2, "0")}.jpeg`,
      ),
  }));
}
