export const CATALOG_STORAGE_KEY = "kushi-agro-catalog";

export const defaultCatalog = [
  {
    id: "01",
    name: "Zanda Executive Range",
    tagline: "Premium quality rice",
    description: "Experience the **extraordinary aroma** and **perfect texture** of our flagship Zanda Executive rice. Harvested from the **fertile plains**, each grain is **meticulously sorted** for a truly **gourmet dining experience**.",
    pack: "25 KG",
    views: 3,
    coverImage: "/images/catalog/product-01/showcase.jpeg",
    accent: "from-[#18432A] to-[#6B8D58]",
    badge: "Top Seller",
  },
  {
    id: "02",
    name: "Zanda",
    variant: "Blue Pack",
    tagline: "Premium quality rice",
    description: "The classic Zanda Blue Pack offers **consistent purity** and **superior grain length**. A staple for households that demand **uncompromising quality** and **authentic taste** in every meal.",
    pack: "25 KG",
    views: 2,
    accent: "from-[#2848A1] to-[#7A89E8]",
    badge: "Top Seller",
  },
  {
    id: "03",
    name: "Zanda Exclusive Range",
    tagline: "Premium quality rice",
    description: "Our Exclusive Range is **double-polished** for a **radiant shine** and **smooth finish**. Ideal for **special occasions**, it provides the **perfect base** for festive rice dishes.",
    pack: "25 KG",
    views: 3,
    coverImage: "/images/catalog/product-03/showcase.jpeg",
    accent: "from-[#A93D2D] to-[#E58B6E]",
  },
  {
    id: "04",
    name: "Small Boss Platinum Range",
    tagline: "Happy Special Blue Lam steam rice",
    description: "Small Boss Platinum features **Blue Lam steam technology**, ensuring that every grain remains **separate and fluffy**. Perfect for **commercial kitchens** and **large gatherings**.",
    pack: "25 KG",
    views: 3,
    coverImage: "/images/catalog/product-04/showcase.jpeg",
    accent: "from-[#6B124E] to-[#F08BBF]",
  },
  {
    id: "05",
    name: "Monsoon Sona Masuri",
    tagline: "1 year old sona masuri rice",
    description: "Naturally **aged for 12 months**, our Monsoon Sona Masuri is the **ultimate choice** for a **light and healthy** diet. Known for its **delicate flavor** and **low glycemic index**.",
    pack: "25 KG",
    views: 2,
    accent: "from-[#9A2915] to-[#F0B23B]",
  },
  {
    id: "06",
    name: "Golden Chilli Economical Range",
    tagline: "new sona masuri rice",
    description: "The Golden Chilli Economical Range brings **premium quality** to every home. **Freshly harvested** and **hygienically packed**, it offers the **best value** without compromising on purity.",
    pack: "25 KG",
    views: 2,
    coverImage: "/images/catalog/product-06/showcase.jpeg",
    accent: "from-[#171717] to-[#828282]",
  },
  {
    id: "07",
    name: "Royal Bullet Rice",
    tagline: "2 years old rnr rice",
    description: "Aged for a full **24 months**, Royal Bullet (RNR) is the **king of short-grain rice**. It offers a **unique nutty aroma** and remains **super soft** even hours after cooking.",
    pack: "25 KG",
    views: 2,
    accent: "from-[#2391D8] to-[#A1D9FF]",
  },
  {
    id: "08",
    name: "Happy Special Premium Sortex",
    tagline: "Premium sortex quality rice",
    description: "Processed using **advanced Sortex technology**, this range is **100% stone-free** and **perfectly graded**. It guarantees a **flawless appearance** and **uniform cooking**.",
    pack: "25 KG",
    views: 3,
    accent: "from-[#3A287C] to-[#BFA2FF]",
  },
  {
    id: "09",
    name: "Happy Special Jeera Rice",
    tagline: "Marriage special biryani colom rice",
    description: "Specially selected for **Biryani and Pulav**, our Jeera Rice features **short, slender grains** that absorb flavors perfectly. The **secret ingredient** for any **celebration feast**.",
    pack: "26 KG",
    views: 1,
    accent: "from-[#171717] to-[#796D5E]",
  },
  {
    id: "10",
    name: "Happy Special Premium Sorted",
    tagline: "Premium sorted quality rice",
    description: "A **meticulously cleaned** and **triple-sorted** rice that offers **maximum purity**. Perfect for families who prioritize **hygiene** and **refined grain quality**.",
    pack: "25 KG",
    views: 2,
    accent: "from-[#22358C] to-[#7AA7FF]",
  },
  {
    id: "11",
    name: "M Platinum Range",
    tagline: "Happy Special Blue Lam steam rice",
    description: "The M Platinum series represents the **pinnacle of steam rice**. Each grain is **steam-cured** to lock in nutrients and ensure a **firm, non-sticky texture** every time.",
    pack: "25 KG",
    views: 2,
    coverImage: "/images/catalog/product-11/showcase.jpeg",
    accent: "from-[#B11F21] to-[#FF8A8D]",
  },
  {
    id: "12",
    name: "M Jeera Rice",
    variant: "Black Pack",
    tagline: "Biriyani Special",
    description: "The **ultimate Biryani rice**. Our Black Pack Jeera Rice is **highly aromatic** and offers the **perfect bite**. A favorite among **professional chefs** for its **consistent results**.",
    pack: "25 KG",
    views: 2,
    coverImage: "/images/catalog/product-12/showcase.jpeg",
    accent: "from-[#111111] to-[#696969]",
    badge: "Biriyani Special",
  },
  {
    id: "13",
    name: "M Jeera Rice",
    variant: "Red Pack",
    tagline: "2 years old rnr rice",
    description: "A **rare find**, this 2-year-old RNR Jeera Rice combines the **aroma of Jeera** with the **softness of aged grains**. The **perfect choice** for traditional **South Indian meals**.",
    pack: "25 KG",
    views: 2,
    accent: "from-[#A51217] to-[#E87073]",
    badge: "Biriyani Special",
  },
  {
    id: "14",
    name: "Royal Bullet Rice",
    variant: "Pink Pack",
    tagline: "Jeera rice marriage special biryani colom rice",
    description: "A **versatile performer**, the Pink Pack is ideal for both **daily meals and festive biryanis**. It offers a **premium mouthfeel** and **delicate fragrance** at an affordable price.",
    pack: "25 KG",
    views: 3,
    accent: "from-[#B2109C] to-[#FF88E4]",
  },
  {
    id: "15",
    name: "Royal Bullet Rice",
    variant: "Green Pack",
    tagline: "Jeera rice marriage special biryani colom rice",
    description: "Our Green Pack focuses on **natural freshness**. Harvested from **eco-friendly farms**, it delivers the **authentic taste of Raichur** in every single grain.",
    pack: "25 KG",
    views: 2,
    accent: "from-[#136838] to-[#7FCC95]",
  },
  {
    id: "16",
    name: "Royal Bullet Rice",
    variant: "Red Pack",
    tagline: "Jeera rice marriage special biryani colom rice",
    description: "The Red Pack is **specially aged** to ensure that it never becomes sticky. It's the **preferred choice** for **catering services** where **volume and quality** both matter.",
    pack: "25 KG",
    views: 3,
    accent: "from-[#941312] to-[#E66B67]",
  },
  {
    id: "17",
    name: "Royal Bullet Rice",
    variant: "Orange Pack",
    tagline: "Jeera rice marriage special biryani colom rice",
    description: "A **rich and flavorful** option, the Orange Pack is known for its **vibrant aroma**. It's **triple-cleaned** to ensure that you get nothing but the **purest rice grains**.",
    pack: "25 KG",
    views: 3,
    accent: "from-[#B96512] to-[#FFBB58]",
  },
  {
    id: "18",
    name: "Royal Bullet Rice",
    variant: "Blue Pack",
    tagline: "Jeera rice marriage special biryani colom rice",
    description: "The Blue Pack Royal Bullet is **exceptionally light** on the stomach. It's **carefully processed** to maintain its **natural oils**, ensuring a **deliciously soft texture**.",
    pack: "25 KG",
    views: 3,
    accent: "from-[#1978BF] to-[#83CCFF]",
  },
  {
    id: "21",
    name: "Vandematharam Special Range",
    tagline: "Premium bullet rice old HMT",
    description: "Vandematharam Special brings you the **legacy of Old HMT**. Known for its **slender grains** and **unmatched taste**, it is the **gold standard** of premium rice.",
    pack: "25 KG",
    views: 2,
    accent: "from-[#A48B14] to-[#F1D45B]",
  },
  {
    id: "22",
    name: "Vande Mataram Premium Sorted",
    tagline: "Raichur Sona Masuri rice",
    description: "Authentic **Raichur Sona Masuri** at its finest. Our Premium Sorted range is **white, clean, and delicious**. A perfect companion for **everyday South Indian cooking**.",
    pack: "10 KG",
    views: 2,
    accent: "from-[#D65C12] to-[#F0C853]",
  },
  {
    id: "23",
    name: "Vande Mataram Premium Sorted",
    tagline: "Premium sorted rice",
    description: "The 25KG family pack of our **Vande Mataram Premium Sorted**. It offers **consistent quality** across the entire bag, ensuring that every meal is as **perfect as the last**.",
    pack: "25 KG",
    views: 3,
    accent: "from-[#D96A1F] to-[#F4D17F]",
  },
  {
    id: "24",
    name: "Vandematharam Gold Range",
    tagline: "One year old raw rice",
    description: "Naturally **aged for 1 year**, the Gold Range offers the **perfect balance** of taste and health. Each grain is **individually inspected** to ensure **peak freshness**.",
    pack: "25 KG",
    views: 3,
    coverImage: "/images/catalog/product-24/view-02.jpeg",
    accent: "from-[#394C9E] to-[#93A4F2]",
  },
  {
    id: "25",
    name: "Vandematharam Gold Range",
    tagline: "Grand old raw rice",
    description: "Our **Grand Old Raw Rice** is aged to perfection, making it **extra fluffy** and **flavor-packed**. A **treasured variety** that has been a family favorite for generations.",
    pack: "25 KG",
    views: 3,
    coverImage: "/images/catalog/product-25/view-02.jpeg",
    accent: "from-[#8B6D10] to-[#D8C15A]",
  },
  {
    id: "26",
    name: "M Platinum Range",
    variant: "Fine Bullet Rice",
    tagline: "Ultra quality fine bullet rice",
    description: "The **ultimate fine bullet rice**. Processed with **extreme precision**, it offers a **smooth, silky finish** and a **delightful aroma** that fills the entire kitchen.",
    pack: "25 KG",
    views: 1,
    coverImage: "/images/catalog/product-26/showcase.jpeg",
    accent: "from-[#9E178A] to-[#F36DDA]",
  },
];

export function buildCatalogProducts(catalog) {
  return catalog.map((product) => {
    const defaultCover = `/images/catalog/product-${product.id}/view-01.jpeg`;
    const coverImage = product.coverImage || defaultCover;
    
    let images = product.images;
    if (!images) {
      images = Array.from(
        { length: product.views },
        (_, index) =>
          `/images/catalog/product-${product.id}/view-${String(index + 1).padStart(2, "0")}.jpeg`
      );
      // If a custom cover image is set (like showcase.jpeg), make sure it's the very first image in the slider
      if (product.coverImage) {
        images = [product.coverImage, ...images];
      }
    }

    return {
      ...product,
      coverImage,
      images,
    };
  });
}
